# Generated by Django 3.2.9 on 2022-02-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_profileuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='forget_pass_token',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
