# Generated by Django 3.2.9 on 2022-02-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_auto_20220208_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registertable',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
